"""Temporary analysis: raw (no filtering) step vs nonstep xCOM/BOS difference.

User request summary:
- Run `main.py` WITHOUT `scripts/apply_post_filter_from_meta.py`.
- Also disable `main.py`'s default prefilter (`--no-meta_prefilter`) to keep raw samples.
- Using the resulting output CSV, test step vs nonstep difference for xCOM/BOS.
- Write outputs under `analysis/initial_posture_strategy_lmm/`.
- Do not modify legacy code; add temp script + temp report only.

Statistical model (matches existing report style):
  DV ~ step_TF + (1|subject)  (REML; lmerTest via Rscript)

DV definitions:
  xCOM_BOS_norm = (xCOM_X - BOS_minX) / (BOS_maxX - BOS_minX)
  - onset: MocapFrame == platform_onset_local
  - 300ms: MocapFrame == platform_onset_local + 30  (100 Hz -> 30 frames)
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
import polars as pl
from statsmodels.stats.multitest import multipletests

# Required display config by repo rule
pl.Config.set_tbl_rows(999)
pl.Config.set_tbl_cols(999)
pl.Config.set_tbl_width_chars(120)


SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[1]

TRIAL_KEYS = ["subject", "velocity", "trial"]


@dataclass(frozen=True)
class SnapshotSpec:
    name: str
    frame_expr: pl.Expr


def _parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--csv",
        type=Path,
        default=SCRIPT_DIR / "tmp_raw_nometa_output" / "all_trials_timeseries_raw_nometa.csv",
        help="Input CSV generated by running main.py with --no-meta_prefilter.",
    )
    ap.add_argument(
        "--platform_xlsm",
        type=Path,
        default=REPO_ROOT / "data" / "perturb_inform.xlsm",
        help="Workbook used to attach step_TF labels (platform sheet).",
    )
    ap.add_argument(
        "--out_dir",
        type=Path,
        default=SCRIPT_DIR,
        help="Output directory for report/results (default: this script folder).",
    )
    ap.add_argument(
        "--frames_300ms",
        type=int,
        default=30,
        help="Frame offset for 300ms snapshot (default: 30 @ 100 Hz).",
    )
    ap.add_argument(
        "--timeout_sec",
        type=int,
        default=900,
        help="Timeout for R lmerTest fitting (seconds).",
    )
    return ap.parse_args()


def _load_timeseries(csv_path: Path) -> pl.DataFrame:
    if not csv_path.exists():
        raise FileNotFoundError(f"input csv not found: {csv_path}")

    df = pl.read_csv(str(csv_path), encoding="utf8-lossy", infer_schema_length=10000)
    if "trial" not in df.columns and "trial_num" in df.columns:
        df = df.rename({"trial_num": "trial"})

    required = {
        "subject",
        "velocity",
        "trial",
        "platform_onset_local",
        "analysis_end_local",
        "MocapFrame",
        "xCOM_X",
        "BOS_minX",
        "BOS_maxX",
    }
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(f"input csv missing required columns: {missing}")

    return df.with_columns(
        pl.col("subject").cast(pl.Utf8).str.strip_chars(),
        pl.col("velocity").cast(pl.Float64, strict=False),
        pl.col("trial").cast(pl.Int64, strict=False),
        pl.col("platform_onset_local").cast(pl.Int64, strict=False),
        pl.col("analysis_end_local").cast(pl.Int64, strict=False),
        pl.col("MocapFrame").cast(pl.Int64, strict=False),
    )


def _load_platform_labels(platform_xlsm: Path) -> pl.DataFrame:
    if not platform_xlsm.exists():
        raise FileNotFoundError(f"platform_xlsm not found: {platform_xlsm}")

    platform = pl.read_excel(str(platform_xlsm), sheet_name="platform")
    required = {"subject", "velocity", "trial", "step_TF", "state", "mixed", "platform_onset", "step_onset"}
    missing = sorted(required - set(platform.columns))
    if missing:
        raise ValueError(f"platform sheet missing required columns: {missing}")

    # Keep join keys + group labels (no filtering here).
    return (
        platform.select(["subject", "velocity", "trial", "step_TF", "state", "mixed", "platform_onset", "step_onset"])
        .with_columns(
            pl.col("subject").cast(pl.Utf8).str.strip_chars(),
            pl.col("velocity").cast(pl.Float64, strict=False),
            pl.col("trial").cast(pl.Int64, strict=False),
            pl.col("step_TF")
            .cast(pl.Utf8, strict=False)
            .str.strip_chars()
            .str.to_lowercase()
            .alias("step_TF"),
            pl.col("state").cast(pl.Utf8, strict=False).str.strip_chars().str.to_lowercase().alias("state"),
            pl.col("mixed").cast(pl.Float64, strict=False),
            pl.col("platform_onset").cast(pl.Float64, strict=False),
            pl.col("step_onset").cast(pl.Float64, strict=False),
        )
    )


def _validate_minimum(df: pl.DataFrame) -> None:
    # 1) keys non-null
    null_counts = (
        df.select([pl.col("subject").is_null().sum().alias("subject_nulls"),
                   pl.col("velocity").is_null().sum().alias("velocity_nulls"),
                   pl.col("trial").is_null().sum().alias("trial_nulls")])
        .row(0)
    )
    if any(int(x) > 0 for x in null_counts):
        raise ValueError(f"key columns contain nulls: subject/velocity/trial nulls={null_counts}")

    # 2) MocapFrame monotonic per trial (cheap check: ensure min diff >= 1 when sorted)
    # This assumes the batch pipeline writes frames in order; we still validate to catch corrupt merges.
    problems = (
        df.sort(TRIAL_KEYS + ["MocapFrame"])
        .group_by(TRIAL_KEYS)
        .agg((pl.col("MocapFrame").diff().drop_nulls().min()).alias("min_diff"))
        .filter(pl.col("min_diff") < 1)
    )
    if problems.height > 0:
        sample = problems.head(5).to_dicts()
        raise ValueError(f"MocapFrame not strictly increasing within trials. Sample: {sample}")

    # 3) platform_onset_local exists and within [1, analysis_end_local]
    onset_audit = (
        df.group_by(TRIAL_KEYS)
        .agg(
            pl.col("platform_onset_local").drop_nulls().first().alias("platform_onset_local"),
            pl.col("analysis_end_local").drop_nulls().first().alias("analysis_end_local"),
        )
        .with_columns(
            (pl.col("platform_onset_local") >= 1).alias("onset_ge_1"),
            (pl.col("platform_onset_local") <= pl.col("analysis_end_local")).alias("onset_le_end"),
        )
        .filter(~(pl.col("onset_ge_1") & pl.col("onset_le_end")))
    )
    if onset_audit.height > 0:
        sample = onset_audit.head(5).to_dicts()
        raise ValueError(f"platform_onset_local out of range. Sample: {sample}")


def _compute_xcom_bos_norm(df: pl.DataFrame) -> pl.DataFrame:
    denom = pl.col("BOS_maxX") - pl.col("BOS_minX")
    return df.with_columns(
        pl.when(denom > 0)
        .then((pl.col("xCOM_X") - pl.col("BOS_minX")) / denom)
        .otherwise(None)
        .alias("xCOM_BOS_norm")
    )


def _build_snapshot(df: pl.DataFrame, spec: SnapshotSpec) -> pl.DataFrame:
    onset = (
        df.group_by(TRIAL_KEYS)
        .agg(pl.col("platform_onset_local").drop_nulls().first().cast(pl.Int64).alias("platform_onset_local"))
        .sort(TRIAL_KEYS)
    )

    snap = (
        df.join(onset, on=TRIAL_KEYS, how="inner")
        .filter(pl.col("MocapFrame") == spec.frame_expr)
        .select(TRIAL_KEYS + ["xCOM_BOS_norm"])
    )

    dup = snap.group_by(TRIAL_KEYS).len().filter(pl.col("len") != 1)
    if dup.height > 0:
        sample = dup.head(5).to_dicts()
        raise ValueError(f"{spec.name} snapshot has non-unique rows. Sample: {sample}")

    return snap.rename({"xCOM_BOS_norm": spec.name})


def _resolve_rscript() -> str:
    which_r = shutil.which("Rscript")
    if which_r:
        return which_r

    conda_prefix = os.environ.get("CONDA_PREFIX")
    if conda_prefix:
        candidate = Path(conda_prefix) / "bin" / "Rscript"
        if candidate.exists():
            return str(candidate)

    raise FileNotFoundError("Rscript not found. Run this script via `conda run -n module python ...`.")


def _build_r_lmm_script(csv_path: str, output_path: str, dv_cols: list[str]) -> str:
    # Only analyze the specified columns (keeps this temp experiment focused).
    dv_vec = ", ".join([f"'{x}'" for x in dv_cols])
    return f"""
library(lmerTest)

data <- read.csv("{csv_path}", stringsAsFactors = FALSE)
data$step_TF <- tolower(trimws(as.character(data$step_TF)))
data$step_TF <- factor(data$step_TF, levels = c("nonstep", "step"))
dv_cols <- c({dv_vec})

results <- data.frame(
  dv = character(),
  estimate = numeric(),
  SE = numeric(),
  df = numeric(),
  t_value = numeric(),
  p_value = numeric(),
  mean_step = numeric(),
  sd_step = numeric(),
  mean_nonstep = numeric(),
  sd_nonstep = numeric(),
  n_step = integer(),
  n_nonstep = integer(),
  converged = logical(),
  stringsAsFactors = FALSE
)

for (dv in dv_cols) {{
  sub <- data[!is.na(data[[dv]]) & !is.na(data$step_TF), ]
  n_s <- sum(sub$step_TF == "step")
  n_ns <- sum(sub$step_TF == "nonstep")

  m_s <- mean(sub[[dv]][sub$step_TF == "step"], na.rm = TRUE)
  sd_s <- sd(sub[[dv]][sub$step_TF == "step"], na.rm = TRUE)
  m_ns <- mean(sub[[dv]][sub$step_TF == "nonstep"], na.rm = TRUE)
  sd_ns <- sd(sub[[dv]][sub$step_TF == "nonstep"], na.rm = TRUE)

  if (n_s == 0 || n_ns == 0) {{
    results <- rbind(results, data.frame(
      dv = dv, estimate = NA, SE = NA, df = NA,
      t_value = NA, p_value = NA,
      mean_step = m_s, sd_step = sd_s,
      mean_nonstep = m_ns, sd_nonstep = sd_ns,
      n_step = n_s, n_nonstep = n_ns, converged = FALSE,
      stringsAsFactors = FALSE
    ))
    next
  }}

  formula_str <- paste0("`", dv, "` ~ step_TF + (1|subject)")
  tryCatch({{
    m <- lmer(as.formula(formula_str), data = sub, REML = TRUE)
    s <- summary(m)
    co <- coef(s)

    row_name <- grep("^step_TFstep$", rownames(co), value = TRUE)[1]
    if (!is.na(row_name)) {{
      est <- co[row_name, "Estimate"]
      se <- co[row_name, "Std. Error"]
      df_val <- co[row_name, "df"]
      t_val <- co[row_name, "t value"]
      p_val <- co[row_name, "Pr(>|t|)"]
    }} else {{
      est <- NA; se <- NA; df_val <- NA; t_val <- NA; p_val <- NA
    }}

    results <- rbind(results, data.frame(
      dv = dv, estimate = est, SE = se, df = df_val,
      t_value = t_val, p_value = p_val,
      mean_step = m_s, sd_step = sd_s,
      mean_nonstep = m_ns, sd_nonstep = sd_ns,
      n_step = n_s, n_nonstep = n_ns, converged = TRUE,
      stringsAsFactors = FALSE
    ))
  }}, error = function(e) {{
    results <<- rbind(results, data.frame(
      dv = dv, estimate = NA, SE = NA, df = NA,
      t_value = NA, p_value = NA,
      mean_step = m_s, sd_step = sd_s,
      mean_nonstep = m_ns, sd_nonstep = sd_ns,
      n_step = n_s, n_nonstep = n_ns, converged = FALSE,
      stringsAsFactors = FALSE
    ))
  }})
}}

write.csv(results, "{output_path}", row.names = FALSE)
cat("LMM fitting complete:", nrow(results), "models\\n")
"""


def _fit_lmm(analysis_df: pd.DataFrame, dv_cols: list[str], timeout_sec: int) -> pd.DataFrame:
    export_cols = TRIAL_KEYS + ["step_TF"] + dv_cols
    export_df = analysis_df[export_cols].copy()

    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".csv",
        delete=False,
        dir=tempfile.gettempdir(),
        newline="",
    ) as f:
        export_df.to_csv(f, index=False)
        data_csv = f.name

    result_csv = tempfile.mktemp(suffix="_lmm_results.csv", dir=tempfile.gettempdir())
    r_script_path = tempfile.mktemp(suffix="_lmm_tmp.R", dir=tempfile.gettempdir())

    try:
        r_code = _build_r_lmm_script(
            data_csv.replace("\\", "/"),
            result_csv.replace("\\", "/"),
            dv_cols=dv_cols,
        )
        Path(r_script_path).write_text(r_code, encoding="utf-8")

        rscript_cmd = _resolve_rscript()
        proc = subprocess.run(
            [rscript_cmd, r_script_path],
            capture_output=True,
            text=True,
            timeout=int(timeout_sec),
        )
        if proc.returncode != 0:
            raise RuntimeError(f"Rscript failed (code={proc.returncode}). stderr:\n{proc.stderr[:2000]}")

        results = pd.read_csv(result_csv)
    finally:
        for p in [data_csv, result_csv, r_script_path]:
            try:
                os.unlink(p)
            except OSError:
                pass

    # p-value correction across the tested DVs (tiny set, but keep consistent with repo report style)
    results["p_fdr"] = np.nan
    p_mask = results["p_value"].notna()
    if int(p_mask.sum()) > 0:
        _, p_fdr, _, _ = multipletests(results.loc[p_mask, "p_value"].values, method="fdr_bh")
        results.loc[p_mask, "p_fdr"] = p_fdr

    def _sig(p: float) -> str:
        if pd.isna(p):
            return ""
        if p < 0.001:
            return "***"
        if p < 0.01:
            return "**"
        if p < 0.05:
            return "*"
        return "n.s."

    results["sig"] = results["p_fdr"].apply(_sig)
    return results


def _write_utf8_sig_csv(df: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    df.to_csv(tmp, index=False, encoding="utf-8-sig")
    tmp.replace(path)


def _write_report(
    *,
    out_path: Path,
    input_csv: Path,
    frames_300ms: int,
    counts: dict[str, int],
    results: pd.DataFrame,
    notes: list[str],
) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # Keep this report concise; it's a short experiment.
    lines: list[str] = []
    lines.append("# TEMP: Raw xCOM/BOS Step vs Nonstep (No Filtering)")
    lines.append("")
    lines.append("## Research Question")
    lines.append("")
    lines.append('**"필터링 없이 거친 표본(raw samples)에서 step vs nonstep 간 xCOM/BOS 차이가 존재하는가?"**')
    lines.append("")
    lines.append("## Data")
    lines.append("")
    lines.append(f"- Input CSV: `{input_csv}`")
    lines.append("- step/nonstep label source: `data/perturb_inform.xlsm` (platform sheet join)")
    lines.append(f"- Trials (step/nonstep usable): **{counts['n_trials_usable']}**")
    lines.append(f"- Subjects (usable): **{counts['n_subjects_usable']}**")
    lines.append(f"- step: **{counts['n_step']}**, nonstep: **{counts['n_nonstep']}**")
    lines.append(f"- 300ms snapshot offset: **+{frames_300ms} frames** (assumes 100 Hz)")
    lines.append("")
    lines.append("## Methodology")
    lines.append("")
    lines.append("- Snapshot 1: `platform_onset_local` (MocapFrame == platform_onset_local)")
    lines.append(f"- Snapshot 2: `platform_onset_local + {frames_300ms}` (if within analysis window)")
    lines.append("- DV: `xCOM_BOS_norm = (xCOM_X - BOS_minX) / (BOS_maxX - BOS_minX)`")
    lines.append("- Model: `DV ~ step_TF + (1|subject)` (REML, `lmerTest`)")
    lines.append("- Multiple comparison: BH-FDR across tested DVs (here: onset, 300ms)")
    lines.append("")
    lines.append("## Results")
    lines.append("")
    # Render a compact markdown table
    show_cols = [
        "dv",
        "estimate",
        "SE",
        "df",
        "t_value",
        "p_value",
        "p_fdr",
        "sig",
        "mean_step",
        "sd_step",
        "mean_nonstep",
        "sd_nonstep",
        "n_step",
        "n_nonstep",
        "converged",
    ]
    table = results[show_cols].copy()
    # format floats for readability
    float_cols = [
        "estimate",
        "SE",
        "df",
        "t_value",
        "p_value",
        "p_fdr",
        "mean_step",
        "sd_step",
        "mean_nonstep",
        "sd_nonstep",
    ]
    for c in float_cols:
        if c in table.columns:
            table[c] = table[c].map(lambda x: "" if pd.isna(x) else f"{x:.6g}")

    lines.append(table.to_markdown(index=False))
    lines.append("")
    lines.append("## Notes / Limitations")
    lines.append("")
    if notes:
        for note in notes:
            lines.append(f"- {note}")
    else:
        lines.append("- (none)")
    lines.append("")
    lines.append("## Reproduction")
    lines.append("")
    lines.append("```bash")
    lines.append("# 1) generate raw output (no meta prefilter)")
    lines.append(
        "conda run --no-capture-output -n module python ../../main.py "
        "--no-meta_prefilter --skip_unmatched --overwrite "
        "--out_dir tmp_raw_nometa_output "
        "--out_csv tmp_raw_nometa_output/all_trials_timeseries_raw_nometa.csv"
    )
    lines.append("")
    lines.append("# 2) run this analysis")
    lines.append(
        "conda run -n module python analysis/initial_posture_strategy_lmm/tmp_analyze_raw_step_nonstep_xcom_bos_lmm.py"
    )
    lines.append("```")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = _parse_args()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    df_ts = _load_timeseries(args.csv)
    _validate_minimum(df_ts)
    df_ts = _compute_xcom_bos_norm(df_ts)

    platform = _load_platform_labels(args.platform_xlsm)

    # Snapshots (onset + 300ms)
    snap_onset = _build_snapshot(
        df_ts,
        SnapshotSpec(name="xCOM_BOS_norm_onset", frame_expr=pl.col("platform_onset_local")),
    )
    snap_300 = _build_snapshot(
        df_ts,
        SnapshotSpec(
            name="xCOM_BOS_norm_300ms",
            frame_expr=(pl.col("platform_onset_local") + int(args.frames_300ms)),
        ),
    )

    snap = (
        # Keep all trials that have either onset or 300ms snapshot available.
        snap_onset.join(snap_300, on=TRIAL_KEYS, how="full", coalesce=True)
        .join(platform, on=TRIAL_KEYS, how="left")
    )

    # Keep only step/nonstep trials for group comparison.
    snap = snap.with_columns(pl.col("step_TF").cast(pl.Utf8, strict=False))
    usable = snap.filter(pl.col("step_TF").is_in(["step", "nonstep"]))

    # Convert to pandas for statsmodels + markdown output.
    analysis_df = usable.to_pandas()

    # Count summary
    counts = {
        "n_trials_usable": int(len(analysis_df)),
        "n_subjects_usable": int(pd.Series(analysis_df["subject"]).nunique(dropna=True)),
        "n_step": int((analysis_df["step_TF"] == "step").sum()),
        "n_nonstep": int((analysis_df["step_TF"] == "nonstep").sum()),
    }

    dv_cols: list[str] = ["xCOM_BOS_norm_onset", "xCOM_BOS_norm_300ms"]
    results = _fit_lmm(analysis_df, dv_cols=dv_cols, timeout_sec=int(args.timeout_sec))

    # Persist outputs under analysis/initial_posture_strategy_lmm (as requested)
    results_out_csv = out_dir / "tmp_raw_xcom_bos_step_vs_nonstep_lmm_results.csv"
    _write_utf8_sig_csv(results, results_out_csv)

    report_out_md = out_dir / "tmp_report_raw_xcom_bos_step_vs_nonstep.md"
    notes = [
        "No filtering applied (no meta_prefilter, no post-filter): dataset includes heterogeneous subjects/trials.",
        "Raw CSV generated with meta_prefilter disabled does not contain step_TF; labels are joined from platform sheet.",
        "Forceplate inertial subtract QC warnings may appear during batch export, but this analysis only uses xCOM/BOS (marker-based).",
    ]
    _write_report(
        out_path=report_out_md,
        input_csv=args.csv,
        frames_300ms=int(args.frames_300ms),
        counts=counts,
        results=results,
        notes=notes,
    )

    print(f"[OK] results: {results_out_csv}")
    print(f"[OK] report:  {report_out_md}")
    print(f"[INFO] usable trials: {counts}")


if __name__ == "__main__":
    main()
