"""Temporary raw analysis: step vs nonstep decomposition of xCOM/BOS terms.

Inputs:
- Raw timeseries CSV generated by:
  `main.py --no-meta_prefilter` (without post-filter script).
- Platform labels from `data/perturb_inform.xlsm` sheet `platform`.

DVs (at onset and +300ms):
- Numerator: xCOM_rel_minX = xCOM_X - BOS_minX
- Denominator: BOS_rangeX = BOS_maxX - BOS_minX
- Ratio: xCOM_BOS_norm = xCOM_rel_minX / BOS_rangeX

Model:
- DV ~ step_TF + (1|subject), REML, lmerTest
- BH-FDR over all tested DVs
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import tempfile
from pathlib import Path

import numpy as np
import pandas as pd
import polars as pl
from statsmodels.stats.multitest import multipletests

pl.Config.set_tbl_rows(999)
pl.Config.set_tbl_cols(999)
pl.Config.set_tbl_width_chars(120)

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[1]
TRIAL_KEYS = ["subject", "velocity", "trial"]


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--csv",
        type=Path,
        default=SCRIPT_DIR / "tmp_raw_nometa_output" / "all_trials_timeseries_raw_nometa.csv",
    )
    ap.add_argument(
        "--platform_xlsm",
        type=Path,
        default=REPO_ROOT / "data" / "perturb_inform.xlsm",
    )
    ap.add_argument("--frames_300ms", type=int, default=30)
    ap.add_argument("--timeout_sec", type=int, default=900)
    ap.add_argument("--out_dir", type=Path, default=SCRIPT_DIR)
    return ap.parse_args()


def load_raw_timeseries(path: Path) -> pl.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"input csv not found: {path}")

    df = pl.read_csv(str(path), encoding="utf8-lossy", infer_schema_length=10000)
    if "trial" not in df.columns and "trial_num" in df.columns:
        df = df.rename({"trial_num": "trial"})

    required = {
        "subject",
        "velocity",
        "trial",
        "platform_onset_local",
        "analysis_end_local",
        "MocapFrame",
        "xCOM_X",
        "BOS_minX",
        "BOS_maxX",
    }
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(f"input csv missing required columns: {missing}")

    out = df.with_columns(
        pl.col("subject").cast(pl.Utf8).str.strip_chars(),
        pl.col("velocity").cast(pl.Float64, strict=False),
        pl.col("trial").cast(pl.Int64, strict=False),
        pl.col("platform_onset_local").cast(pl.Int64, strict=False),
        pl.col("analysis_end_local").cast(pl.Int64, strict=False),
        pl.col("MocapFrame").cast(pl.Int64, strict=False),
    )
    return out


def load_platform_labels(platform_xlsm: Path) -> pl.DataFrame:
    if not platform_xlsm.exists():
        raise FileNotFoundError(f"platform_xlsm not found: {platform_xlsm}")

    platform = pl.read_excel(str(platform_xlsm), sheet_name="platform")
    required = {"subject", "velocity", "trial", "step_TF", "state", "mixed"}
    missing = sorted(required - set(platform.columns))
    if missing:
        raise ValueError(f"platform sheet missing required columns: {missing}")

    return (
        platform.select(["subject", "velocity", "trial", "step_TF", "state", "mixed"])
        .with_columns(
            pl.col("subject").cast(pl.Utf8).str.strip_chars(),
            pl.col("velocity").cast(pl.Float64, strict=False),
            pl.col("trial").cast(pl.Int64, strict=False),
            pl.col("step_TF").cast(pl.Utf8, strict=False).str.strip_chars().str.to_lowercase(),
            pl.col("state").cast(pl.Utf8, strict=False).str.strip_chars().str.to_lowercase(),
            pl.col("mixed").cast(pl.Float64, strict=False),
        )
    )


def validate_minimum(df: pl.DataFrame) -> None:
    key_nulls = (
        df.select(
            pl.col("subject").is_null().sum().alias("subject"),
            pl.col("velocity").is_null().sum().alias("velocity"),
            pl.col("trial").is_null().sum().alias("trial"),
        )
        .row(0)
    )
    if any(int(x) > 0 for x in key_nulls):
        raise ValueError(f"null keys found subject/velocity/trial={key_nulls}")

    monotonic_bad = (
        df.sort(TRIAL_KEYS + ["MocapFrame"])
        .group_by(TRIAL_KEYS)
        .agg(pl.col("MocapFrame").diff().drop_nulls().min().alias("min_diff"))
        .filter(pl.col("min_diff") < 1)
    )
    if monotonic_bad.height > 0:
        sample = monotonic_bad.head(5).to_dicts()
        raise ValueError(f"MocapFrame not monotonic. sample={sample}")

    onset_bad = (
        df.group_by(TRIAL_KEYS)
        .agg(
            pl.col("platform_onset_local").drop_nulls().first().alias("platform_onset_local"),
            pl.col("analysis_end_local").drop_nulls().first().alias("analysis_end_local"),
        )
        .filter((pl.col("platform_onset_local") < 1) | (pl.col("platform_onset_local") > pl.col("analysis_end_local")))
    )
    if onset_bad.height > 0:
        sample = onset_bad.head(5).to_dicts()
        raise ValueError(f"platform_onset_local out of trial range. sample={sample}")


def add_decompose_terms(df: pl.DataFrame) -> pl.DataFrame:
    denom = pl.col("BOS_maxX") - pl.col("BOS_minX")
    return df.with_columns(
        (pl.col("xCOM_X") - pl.col("BOS_minX")).alias("xCOM_rel_minX"),
        denom.alias("BOS_rangeX"),
        pl.when(denom > 0)
        .then((pl.col("xCOM_X") - pl.col("BOS_minX")) / denom)
        .otherwise(None)
        .alias("xCOM_BOS_norm"),
    )


def build_snapshot(df: pl.DataFrame, frame_expr: pl.Expr, suffix: str) -> pl.DataFrame:
    snap = (
        df.filter(pl.col("MocapFrame") == frame_expr)
        .select(TRIAL_KEYS + ["xCOM_rel_minX", "BOS_rangeX", "xCOM_BOS_norm"])
        .rename(
            {
                "xCOM_rel_minX": f"xCOM_rel_minX_{suffix}",
                "BOS_rangeX": f"BOS_rangeX_{suffix}",
                "xCOM_BOS_norm": f"xCOM_BOS_norm_{suffix}",
            }
        )
    )

    dup = snap.group_by(TRIAL_KEYS).len().filter(pl.col("len") != 1)
    if dup.height > 0:
        sample = dup.head(5).to_dicts()
        raise ValueError(f"snapshot duplicate/non-unique rows at {suffix}. sample={sample}")

    return snap


def resolve_rscript() -> str:
    which = shutil.which("Rscript")
    if which:
        return which
    conda_prefix = os.environ.get("CONDA_PREFIX")
    if conda_prefix:
        candidate = Path(conda_prefix) / "bin" / "Rscript"
        if candidate.exists():
            return str(candidate)
    raise FileNotFoundError("Rscript not found in current environment.")


def build_r_code(csv_path: str, out_path: str, dv_cols: list[str]) -> str:
    dv_vec = ", ".join([f"'{dv}'" for dv in dv_cols])
    return f"""
library(lmerTest)

data <- read.csv("{csv_path}", stringsAsFactors = FALSE)
data$step_TF <- tolower(trimws(as.character(data$step_TF)))
data$step_TF <- factor(data$step_TF, levels = c("nonstep", "step"))
dv_cols <- c({dv_vec})

results <- data.frame(
  dv = character(),
  estimate = numeric(),
  SE = numeric(),
  df = numeric(),
  t_value = numeric(),
  p_value = numeric(),
  mean_step = numeric(),
  sd_step = numeric(),
  mean_nonstep = numeric(),
  sd_nonstep = numeric(),
  n_step = integer(),
  n_nonstep = integer(),
  converged = logical(),
  stringsAsFactors = FALSE
)

for (dv in dv_cols) {{
  sub <- data[!is.na(data[[dv]]) & !is.na(data$step_TF), ]
  n_s <- sum(sub$step_TF == "step")
  n_ns <- sum(sub$step_TF == "nonstep")

  m_s <- mean(sub[[dv]][sub$step_TF == "step"], na.rm = TRUE)
  sd_s <- sd(sub[[dv]][sub$step_TF == "step"], na.rm = TRUE)
  m_ns <- mean(sub[[dv]][sub$step_TF == "nonstep"], na.rm = TRUE)
  sd_ns <- sd(sub[[dv]][sub$step_TF == "nonstep"], na.rm = TRUE)

  if (n_s == 0 || n_ns == 0) {{
    results <- rbind(results, data.frame(
      dv = dv, estimate = NA, SE = NA, df = NA,
      t_value = NA, p_value = NA,
      mean_step = m_s, sd_step = sd_s,
      mean_nonstep = m_ns, sd_nonstep = sd_ns,
      n_step = n_s, n_nonstep = n_ns, converged = FALSE,
      stringsAsFactors = FALSE
    ))
    next
  }}

  formula_str <- paste0("`", dv, "` ~ step_TF + (1|subject)")
  tryCatch({{
    model <- lmer(as.formula(formula_str), data = sub, REML = TRUE)
    s <- summary(model)
    co <- coef(s)

    row_name <- grep("^step_TFstep$", rownames(co), value = TRUE)[1]
    if (!is.na(row_name)) {{
      est <- co[row_name, "Estimate"]
      se <- co[row_name, "Std. Error"]
      df_val <- co[row_name, "df"]
      t_val <- co[row_name, "t value"]
      p_val <- co[row_name, "Pr(>|t|)"]
    }} else {{
      est <- NA; se <- NA; df_val <- NA; t_val <- NA; p_val <- NA
    }}

    results <- rbind(results, data.frame(
      dv = dv, estimate = est, SE = se, df = df_val,
      t_value = t_val, p_value = p_val,
      mean_step = m_s, sd_step = sd_s,
      mean_nonstep = m_ns, sd_nonstep = sd_ns,
      n_step = n_s, n_nonstep = n_ns, converged = TRUE,
      stringsAsFactors = FALSE
    ))
  }}, error = function(e) {{
    results <<- rbind(results, data.frame(
      dv = dv, estimate = NA, SE = NA, df = NA,
      t_value = NA, p_value = NA,
      mean_step = m_s, sd_step = sd_s,
      mean_nonstep = m_ns, sd_nonstep = sd_ns,
      n_step = n_s, n_nonstep = n_ns, converged = FALSE,
      stringsAsFactors = FALSE
    ))
  }})
}}

write.csv(results, "{out_path}", row.names = FALSE)
cat("LMM fitting complete:", nrow(results), "models\\n")
"""


def fit_lmm(df: pd.DataFrame, dv_cols: list[str], timeout_sec: int) -> pd.DataFrame:
    export_cols = TRIAL_KEYS + ["step_TF"] + dv_cols
    export_df = df[export_cols].copy()

    with tempfile.NamedTemporaryFile(mode="w", suffix=".csv", delete=False, dir=tempfile.gettempdir(), newline="") as f:
        export_df.to_csv(f, index=False)
        csv_path = f.name

    result_csv = tempfile.mktemp(suffix="_decompose_lmm.csv", dir=tempfile.gettempdir())
    r_path = tempfile.mktemp(suffix="_decompose_lmm.R", dir=tempfile.gettempdir())

    try:
        r_code = build_r_code(csv_path.replace("\\", "/"), result_csv.replace("\\", "/"), dv_cols)
        Path(r_path).write_text(r_code, encoding="utf-8")

        rscript = resolve_rscript()
        proc = subprocess.run([rscript, r_path], capture_output=True, text=True, timeout=int(timeout_sec))
        if proc.returncode != 0:
            raise RuntimeError(f"Rscript failed code={proc.returncode}\n{proc.stderr[:2000]}")

        out = pd.read_csv(result_csv)
    finally:
        for p in [csv_path, result_csv, r_path]:
            try:
                os.unlink(p)
            except OSError:
                pass

    out["p_fdr"] = np.nan
    mask = out["p_value"].notna()
    if int(mask.sum()) > 0:
        _, p_fdr, _, _ = multipletests(out.loc[mask, "p_value"].values, method="fdr_bh")
        out.loc[mask, "p_fdr"] = p_fdr

    def to_sig(p: float) -> str:
        if pd.isna(p):
            return ""
        if p < 0.001:
            return "***"
        if p < 0.01:
            return "**"
        if p < 0.05:
            return "*"
        return "n.s."

    out["sig"] = out["p_fdr"].apply(to_sig)
    return out


def write_utf8_sig_csv(df: pd.DataFrame, out_csv: Path) -> None:
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    tmp = out_csv.with_suffix(out_csv.suffix + ".tmp")
    df.to_csv(tmp, index=False, encoding="utf-8-sig")
    tmp.replace(out_csv)


def write_report(
    out_md: Path,
    input_csv: Path,
    n_trials: int,
    n_subjects: int,
    n_step: int,
    n_nonstep: int,
    results: pd.DataFrame,
) -> None:
    view_cols = [
        "dv",
        "estimate",
        "SE",
        "df",
        "t_value",
        "p_value",
        "p_fdr",
        "sig",
        "mean_step",
        "sd_step",
        "mean_nonstep",
        "sd_nonstep",
        "n_step",
        "n_nonstep",
        "converged",
    ]
    table = results[view_cols].copy()
    float_cols = [
        "estimate",
        "SE",
        "df",
        "t_value",
        "p_value",
        "p_fdr",
        "mean_step",
        "sd_step",
        "mean_nonstep",
        "sd_nonstep",
    ]
    for col in float_cols:
        table[col] = table[col].map(lambda x: "" if pd.isna(x) else f"{x:.6g}")

    lines: list[str] = []
    lines.append("# TEMP: Raw xCOM/BOS Decomposition LMM (Step vs Nonstep)")
    lines.append("")
    lines.append("## Research Question")
    lines.append("")
    lines.append("**Does step vs nonstep difference come from xCOM numerator, BOS denominator, or both in raw samples?**")
    lines.append("")
    lines.append("## Data")
    lines.append("")
    lines.append(f"- Input CSV: `{input_csv}`")
    lines.append(f"- Trials: **{n_trials}**, Subjects: **{n_subjects}**, step=**{n_step}**, nonstep=**{n_nonstep}**")
    lines.append("")
    lines.append("## Method")
    lines.append("")
    lines.append("- Snapshot events: onset (`platform_onset_local`), 300ms (`platform_onset_local + 30`)")
    lines.append("- DVs: `xCOM_rel_minX`, `BOS_rangeX`, `xCOM_BOS_norm` at both events")
    lines.append("- Model: `DV ~ step_TF + (1|subject)` (REML, `lmerTest`), BH-FDR over 6 DVs")
    lines.append("")
    lines.append("## Results")
    lines.append("")
    lines.append(table.to_markdown(index=False))
    lines.append("")
    lines.append("## Reproduction")
    lines.append("")
    lines.append("```bash")
    lines.append("conda run -n module python analysis/initial_posture_strategy_lmm/tmp_analyze_raw_step_nonstep_xcom_bos_decompose_lmm.py")
    lines.append("```")
    lines.append("")
    out_md.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    ts = load_raw_timeseries(args.csv)
    validate_minimum(ts)
    ts = add_decompose_terms(ts)

    onset_expr = pl.col("platform_onset_local")
    frame_300_expr = pl.col("platform_onset_local") + int(args.frames_300ms)

    snap_onset = build_snapshot(ts, onset_expr, "onset")
    snap_300 = build_snapshot(ts, frame_300_expr, "300ms")
    platform = load_platform_labels(args.platform_xlsm)

    merged = (
        snap_onset.join(snap_300, on=TRIAL_KEYS, how="full", coalesce=True)
        .join(platform, on=TRIAL_KEYS, how="left")
        .with_columns(pl.col("step_TF").cast(pl.Utf8, strict=False))
    )
    usable = merged.filter(pl.col("step_TF").is_in(["step", "nonstep"]))
    pdf = usable.to_pandas()

    n_trials = int(len(pdf))
    n_subjects = int(pdf["subject"].nunique(dropna=True))
    n_step = int((pdf["step_TF"] == "step").sum())
    n_nonstep = int((pdf["step_TF"] == "nonstep").sum())

    dv_cols = [
        "xCOM_rel_minX_onset",
        "BOS_rangeX_onset",
        "xCOM_BOS_norm_onset",
        "xCOM_rel_minX_300ms",
        "BOS_rangeX_300ms",
        "xCOM_BOS_norm_300ms",
    ]
    lmm = fit_lmm(pdf, dv_cols, timeout_sec=int(args.timeout_sec))

    out_csv = out_dir / "tmp_raw_xcom_bos_decompose_lmm_results.csv"
    out_md = out_dir / "tmp_report_raw_xcom_bos_decompose.md"
    write_utf8_sig_csv(lmm, out_csv)
    write_report(out_md, args.csv, n_trials, n_subjects, n_step, n_nonstep, lmm)

    print(f"[OK] results: {out_csv}")
    print(f"[OK] report:  {out_md}")
    print(
        "[INFO] counts: "
        f"trials={n_trials}, subjects={n_subjects}, step={n_step}, nonstep={n_nonstep}"
    )


if __name__ == "__main__":
    main()

