"""TEMP: Raw (no-filter) DV1 LMM, foot-length normalized vs absolute cm.

Goal
----
For the raw batch output generated by running:
  `main.py --no-meta_prefilter`
re-run step vs nonstep LMM for DV1 in two representations:

  DV1_norm = (xCOM_hof - BOS_rear) / foot_len_m    [unitless]
  DV1_abs_cm = (xCOM_hof - BOS_rear) * 100         [cm]

Events
------
- platform onset: MocapFrame == platform_onset_local
- step onset: MocapFrame == step_onset_eval
  (step_onset_eval policy matches xCOM&BOS_normalization analysis:
    - step trial: step_onset_local
    - otherwise: subject-velocity mean step_onset_local from step trials
    - fallback: prefilter platform subject-velocity mean using raw events)

Model
-----
DV ~ step_TF + (1|subject), REML, lmerTest
BH-FDR over 4 DVs (2 events x 2 representations)
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np
import pandas as pd
import polars as pl
from statsmodels.stats.multitest import multipletests

pl.Config.set_tbl_rows(999)
pl.Config.set_tbl_cols(999)
pl.Config.set_tbl_width_chars(120)

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

TRIAL_KEYS = ["subject", "velocity", "trial"]
G = 9.81


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--csv",
        type=Path,
        default=SCRIPT_DIR / "tmp_raw_nometa_output" / "all_trials_timeseries_raw_nometa.csv",
    )
    ap.add_argument(
        "--platform_xlsm",
        type=Path,
        default=REPO_ROOT / "data" / "perturb_inform.xlsm",
    )
    ap.add_argument("--out_dir", type=Path, default=SCRIPT_DIR)
    ap.add_argument("--timeout_sec", type=int, default=900)
    ap.add_argument("--dry-run", action="store_true")
    return ap.parse_args()


def load_raw_csv(path: Path) -> pl.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"input csv not found: {path}")
    df = pl.read_csv(str(path), encoding="utf8-lossy", infer_schema_length=10000)
    if "trial" not in df.columns and "trial_num" in df.columns:
        df = df.rename({"trial_num": "trial"})
    required = {
        "subject",
        "velocity",
        "trial",
        "platform_onset_local",
        "step_onset_local",
        "analysis_end_local",
        "MocapFrame",
        "COM_X",
        "vCOM_X",
        "BOS_minX",
    }
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(f"raw csv missing required columns: {missing}")

    return df.with_columns(
        pl.col("subject").cast(pl.Utf8).str.strip_chars(),
        pl.col("velocity").cast(pl.Float64, strict=False),
        pl.col("trial").cast(pl.Int64, strict=False),
        pl.col("platform_onset_local").cast(pl.Int64, strict=False),
        pl.col("step_onset_local").cast(pl.Int64, strict=False),
        pl.col("analysis_end_local").cast(pl.Int64, strict=False),
        pl.col("MocapFrame").cast(pl.Int64, strict=False),
        pl.col("COM_X").cast(pl.Float64, strict=False),
        pl.col("vCOM_X").cast(pl.Float64, strict=False),
        pl.col("BOS_minX").cast(pl.Float64, strict=False),
    )


def _normalize_trial_types(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    out["subject"] = out["subject"].astype(str).str.strip()
    out["velocity"] = pd.to_numeric(out["velocity"], errors="coerce")
    out["trial"] = pd.to_numeric(out["trial"], errors="coerce").astype("Int64")
    return out


def load_platform_sheet(path: Path) -> pd.DataFrame:
    df = pd.read_excel(str(path), sheet_name="platform")
    required = {"subject", "velocity", "trial", "step_TF", "platform_onset", "step_onset"}
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(f"platform sheet missing required columns: {missing}")

    out = df[["subject", "velocity", "trial", "step_TF", "platform_onset", "step_onset"]].copy()
    out = _normalize_trial_types(out)
    out["step_TF"] = out["step_TF"].astype(str).str.strip().str.lower()
    out["platform_onset"] = pd.to_numeric(out["platform_onset"], errors="coerce")
    out["step_onset"] = pd.to_numeric(out["step_onset"], errors="coerce")
    return out


def load_anthropometrics_from_meta(path: Path) -> pd.DataFrame:
    raw = pd.read_excel(str(path), sheet_name="meta")
    label_col = raw.columns[0]
    raw[label_col] = raw[label_col].astype(str).str.strip()

    required_rows = ["키", "다리길이", "발길이_왼", "발길이_오른"]
    sub = raw[raw[label_col].isin(required_rows)].copy()
    missing_rows = [x for x in required_rows if x not in sub[label_col].tolist()]
    if missing_rows:
        raise ValueError(f"meta sheet missing required anthropometric rows: {missing_rows}")

    records: list[dict] = []
    for _, row in sub.iterrows():
        metric = str(row[label_col]).strip()
        for subject, value in row.iloc[1:].items():
            records.append({"subject": str(subject).strip(), "metric": metric, "value": value})

    long_df = pd.DataFrame(records)
    wide = (
        long_df.pivot_table(index="subject", columns="metric", values="value", aggfunc="first")
        .reset_index()
        .rename_axis(None, axis=1)
    )
    for col in required_rows:
        wide[col] = pd.to_numeric(wide[col], errors="coerce")

    wide = wide.rename(
        columns={
            "키": "height_cm",
            "다리길이": "leg_len_cm",
            "발길이_왼": "foot_len_left_mm",
            "발길이_오른": "foot_len_right_mm",
        }
    )
    wide["foot_len_m"] = ((wide["foot_len_left_mm"] + wide["foot_len_right_mm"]) / 2.0) / 1000.0
    wide["height_m"] = wide["height_cm"] / 100.0
    wide["leg_len_m"] = wide["leg_len_cm"] / 100.0
    return wide[["subject", "height_m", "foot_len_m"]].copy()


def build_frame_bounds(df: pl.DataFrame) -> pd.DataFrame:
    fb = (
        df.group_by(TRIAL_KEYS)
        .agg(
            pl.col("platform_onset_local").drop_nulls().first().alias("platform_onset_local"),
            pl.col("step_onset_local").drop_nulls().first().alias("step_onset_local"),
            pl.col("analysis_end_local").drop_nulls().first().alias("analysis_end_local"),
        )
        .sort(TRIAL_KEYS)
        .to_pandas()
    )
    fb["platform_onset_local"] = pd.to_numeric(fb["platform_onset_local"], errors="coerce")
    fb["step_onset_local"] = pd.to_numeric(fb["step_onset_local"], errors="coerce")
    fb["analysis_end_local"] = pd.to_numeric(fb["analysis_end_local"], errors="coerce")
    return fb


def compute_trial_event_frames(frame_bounds: pd.DataFrame, platform: pd.DataFrame) -> pd.DataFrame:
    trials = frame_bounds.copy()

    plat = platform[TRIAL_KEYS + ["step_TF", "platform_onset", "step_onset"]].drop_duplicates().copy()
    trials = trials.merge(plat, on=TRIAL_KEYS, how="left")
    trials = trials[trials["step_TF"].isin(["step", "nonstep"])].reset_index(drop=True)

    trials["step_onset_eval"] = np.nan
    step_mask = (trials["step_TF"] == "step") & trials["step_onset_local"].notna()
    trials.loc[step_mask, "step_onset_eval"] = trials.loc[step_mask, "step_onset_local"]

    step_means = (
        trials.loc[step_mask]
        .groupby(["subject", "velocity"], as_index=False)["step_onset_local"]
        .mean()
        .rename(columns={"step_onset_local": "mean_step_onset_sv"})
    )

    platform_onset_local_ref_values = (
        trials["platform_onset_local"].dropna().round().astype("Int64").dropna().astype(int)
    )
    if len(platform_onset_local_ref_values) == 0:
        platform_onset_local_ref = 101
    else:
        platform_onset_local_ref = int(pd.Series(platform_onset_local_ref_values).mode().iloc[0])

    prefilter_step_means = (
        platform.loc[
            (platform["step_TF"] == "step")
            & platform["step_onset"].notna()
            & platform["platform_onset"].notna(),
            ["subject", "velocity", "step_onset", "platform_onset"],
        ]
        .assign(
            step_onset_local_prefilter=lambda x: (
                x["step_onset"] - x["platform_onset"] + float(platform_onset_local_ref)
            )
        )
        .groupby(["subject", "velocity"], as_index=False)["step_onset_local_prefilter"]
        .mean()
    )

    trials = trials.merge(step_means, on=["subject", "velocity"], how="left")
    trials = trials.merge(prefilter_step_means, on=["subject", "velocity"], how="left")

    missing_eval = trials["step_onset_eval"].isna()
    trials.loc[missing_eval & trials["mean_step_onset_sv"].notna(), "step_onset_eval"] = trials.loc[
        missing_eval & trials["mean_step_onset_sv"].notna(), "mean_step_onset_sv"
    ]
    missing_eval = trials["step_onset_eval"].isna()
    trials.loc[
        missing_eval & trials["step_onset_local_prefilter"].notna(), "step_onset_eval"
    ] = trials.loc[missing_eval & trials["step_onset_local_prefilter"].notna(), "step_onset_local_prefilter"]

    return trials


def build_snapshot(df: pl.DataFrame, trials: pd.DataFrame, frame_col: str, suffix: str) -> pd.DataFrame:
    key_cols = TRIAL_KEYS + [frame_col]
    needed = trials[key_cols].copy()
    needed[frame_col] = pd.to_numeric(needed[frame_col], errors="coerce")
    needed = needed.dropna(subset=[frame_col])
    needed[frame_col] = needed[frame_col].round().astype(int)

    snap = (
        df.join(pl.from_pandas(needed), on=TRIAL_KEYS, how="inner")
        .filter(pl.col("MocapFrame") == pl.col(frame_col))
        .select(TRIAL_KEYS + ["COM_X", "vCOM_X", "BOS_minX"])
        .rename(
            {
                "COM_X": f"COM_X_{suffix}",
                "vCOM_X": f"vCOM_X_{suffix}",
                "BOS_minX": f"BOS_rear_{suffix}",
            }
        )
        .to_pandas()
    )

    dup = snap.groupby(TRIAL_KEYS).size().reset_index(name="n").query("n != 1")
    if len(dup) > 0:
        raise ValueError(f"non-unique snapshot rows at {suffix}, sample:\n{dup.head(5)}")

    return snap


def _candidate_rscripts() -> list[Path]:
    candidates: list[Path] = []
    which_r = shutil.which("Rscript")
    if which_r:
        candidates.append(Path(which_r))
    conda_prefix = os.environ.get("CONDA_PREFIX")
    if conda_prefix:
        cp = Path(conda_prefix)
        candidates.extend(
            [
                cp / "bin" / "Rscript",
                cp / "Scripts" / "Rscript.exe",
                cp / "lib" / "R" / "bin" / "Rscript",
                cp / "lib" / "R" / "bin" / "x64" / "Rscript.exe",
            ]
        )
    if os.name == "nt":
        candidates.append(Path(r"C:\\Users\\Alice\\miniconda3\\envs\\module\\lib\\R\\bin\\x64\\Rscript.exe"))
    deduped: list[Path] = []
    seen: set[str] = set()
    for p in candidates:
        s = str(p)
        if s in seen:
            continue
        seen.add(s)
        deduped.append(p)
    return deduped


def resolve_r_runtime() -> tuple[str, dict[str, str]]:
    candidates = _candidate_rscripts()
    resolved: Path | None = None
    for c in candidates:
        if c.exists():
            resolved = c
            break
    if resolved is None:
        tried = ", ".join(str(p) for p in candidates) if candidates else "(no candidates)"
        raise FileNotFoundError(f"Rscript not found. tried: {tried}")
    env = os.environ.copy()
    env["PATH"] = str(resolved.parent) + os.pathsep + env.get("PATH", "")
    return str(resolved), env


def build_r_lmm_script(csv_path: str, output_path: str, dv_cols: list[str]) -> str:
    dv_vec = ", ".join([f"'{x}'" for x in dv_cols])
    return f"""
library(lmerTest)

data <- read.csv("{csv_path}", stringsAsFactors = FALSE)
data$step_TF <- tolower(trimws(as.character(data$step_TF)))
data$step_TF <- factor(data$step_TF, levels = c("nonstep", "step"))
dv_cols <- c({dv_vec})

results <- data.frame(
  dv = character(),
  estimate = numeric(),
  SE = numeric(),
  df = numeric(),
  t_value = numeric(),
  p_value = numeric(),
  mean_step = numeric(),
  sd_step = numeric(),
  mean_nonstep = numeric(),
  sd_nonstep = numeric(),
  n_step = integer(),
  n_nonstep = integer(),
  converged = logical(),
  stringsAsFactors = FALSE
)

for (dv in dv_cols) {{
  sub <- data[!is.na(data[[dv]]) & !is.na(data$step_TF), ]
  n_s <- sum(sub$step_TF == "step")
  n_ns <- sum(sub$step_TF == "nonstep")

  m_s <- mean(sub[[dv]][sub$step_TF == "step"], na.rm = TRUE)
  sd_s <- sd(sub[[dv]][sub$step_TF == "step"], na.rm = TRUE)
  m_ns <- mean(sub[[dv]][sub$step_TF == "nonstep"], na.rm = TRUE)
  sd_ns <- sd(sub[[dv]][sub$step_TF == "nonstep"], na.rm = TRUE)

  if (n_s == 0 || n_ns == 0) {{
    results <- rbind(results, data.frame(
      dv = dv, estimate = NA, SE = NA, df = NA,
      t_value = NA, p_value = NA,
      mean_step = m_s, sd_step = sd_s,
      mean_nonstep = m_ns, sd_nonstep = sd_ns,
      n_step = n_s, n_nonstep = n_ns, converged = FALSE,
      stringsAsFactors = FALSE
    ))
    next
  }}

  formula_str <- paste0("`", dv, "` ~ step_TF + (1|subject)")
  tryCatch({{
    m <- lmer(as.formula(formula_str), data = sub, REML = TRUE)
    s <- summary(m)
    co <- coef(s)

    row_name <- grep("^step_TFstep$", rownames(co), value = TRUE)[1]
    if (!is.na(row_name)) {{
      est <- co[row_name, "Estimate"]
      se <- co[row_name, "Std. Error"]
      df_val <- co[row_name, "df"]
      t_val <- co[row_name, "t value"]
      p_val <- co[row_name, "Pr(>|t|)"]
    }} else {{
      est <- NA; se <- NA; df_val <- NA; t_val <- NA; p_val <- NA
    }}

    results <- rbind(results, data.frame(
      dv = dv, estimate = est, SE = se, df = df_val,
      t_value = t_val, p_value = p_val,
      mean_step = m_s, sd_step = sd_s,
      mean_nonstep = m_ns, sd_nonstep = sd_ns,
      n_step = n_s, n_nonstep = n_ns, converged = TRUE,
      stringsAsFactors = FALSE
    ))
  }}, error = function(e) {{
    results <<- rbind(results, data.frame(
      dv = dv, estimate = NA, SE = NA, df = NA,
      t_value = NA, p_value = NA,
      mean_step = m_s, sd_step = sd_s,
      mean_nonstep = m_ns, sd_nonstep = sd_ns,
      n_step = n_s, n_nonstep = n_ns, converged = FALSE,
      stringsAsFactors = FALSE
    ))
  }})
}}

write.csv(results, "{output_path}", row.names = FALSE)
cat("LMM fitting complete:", nrow(results), "models\\n")
"""


def fit_lmm_all(analysis_df: pd.DataFrame, dv_cols: list[str], timeout_sec: int) -> pd.DataFrame:
    export_cols = TRIAL_KEYS + ["step_TF"] + dv_cols
    export_df = analysis_df[export_cols].copy()

    with tempfile.NamedTemporaryFile(mode="w", suffix=".csv", delete=False, dir=tempfile.gettempdir(), newline="") as f:
        export_df.to_csv(f, index=False)
        data_csv = f.name

    result_csv = tempfile.mktemp(suffix="_dv1_raw_lmm_results.csv", dir=tempfile.gettempdir())
    r_script = tempfile.mktemp(suffix="_dv1_raw_lmm.R", dir=tempfile.gettempdir())

    try:
        r_code = build_r_lmm_script(
            data_csv.replace("\\", "/"),
            result_csv.replace("\\", "/"),
            dv_cols=dv_cols,
        )
        Path(r_script).write_text(r_code, encoding="utf-8")

        rscript_cmd, r_env = resolve_r_runtime()
        proc = subprocess.run([rscript_cmd, r_script], capture_output=True, text=True, timeout=int(timeout_sec), env=r_env)
        if proc.returncode != 0:
            raise RuntimeError(f"Rscript failed code={proc.returncode}\n{proc.stderr[:2000]}")

        results = pd.read_csv(result_csv)
    finally:
        for p in [data_csv, result_csv, r_script]:
            try:
                os.unlink(p)
            except OSError:
                pass

    results["p_fdr"] = np.nan
    mask = results["p_value"].notna()
    if int(mask.sum()) > 0:
        _, p_fdr, _, _ = multipletests(results.loc[mask, "p_value"].values, method="fdr_bh")
        results.loc[mask, "p_fdr"] = p_fdr

    def _sig(p: float) -> str:
        if pd.isna(p):
            return ""
        if p < 0.001:
            return "***"
        if p < 0.01:
            return "**"
        if p < 0.05:
            return "*"
        return "n.s."

    results["sig"] = results["p_fdr"].apply(_sig)
    return results


def write_utf8_sig_csv(df: pd.DataFrame, out_csv: Path) -> None:
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    tmp = out_csv.with_suffix(out_csv.suffix + ".tmp")
    df.to_csv(tmp, index=False, encoding="utf-8-sig")
    tmp.replace(out_csv)


def main() -> None:
    args = parse_args()

    raw_ts = load_raw_csv(args.csv)
    frame_bounds = build_frame_bounds(raw_ts)
    platform = load_platform_sheet(args.platform_xlsm)
    trials = compute_trial_event_frames(frame_bounds, platform)
    anth = load_anthropometrics_from_meta(args.platform_xlsm)

    # Height is required for xCOM_hof. Foot length is optional (DV1_norm only).
    bad_height = anth[anth["height_m"].isna() | (anth["height_m"] <= 0)]
    if len(bad_height) > 0:
        sample = bad_height.head(5).to_dict(orient="records")
        raise ValueError(f"invalid height_m in meta sheet. sample={sample}")

    # build snapshots in mocap-frame domain
    snap_onset = build_snapshot(raw_ts, trials, "platform_onset_local", "platform_onset")
    snap_step = build_snapshot(raw_ts, trials, "step_onset_eval", "step_onset")

    base = trials[TRIAL_KEYS + ["step_TF"]].drop_duplicates().copy()
    base = base.merge(anth, on="subject", how="left")
    base = base.merge(snap_onset, on=TRIAL_KEYS, how="left")
    base = base.merge(snap_step, on=TRIAL_KEYS, how="left")

    # compute DV1 for both events
    def compute_dv_for_event(event: str) -> None:
        com = base[f"COM_X_{event}"]
        vcom = base[f"vCOM_X_{event}"]
        bos = base[f"BOS_rear_{event}"]
        height_m = base["height_m"]
        foot_m = base["foot_len_m"]

        omega0 = np.sqrt(G / height_m)
        xcom_hof = com + vcom / omega0
        dv_raw_m = xcom_hof - bos
        base[f"DV1_norm_{event}"] = np.where(pd.to_numeric(foot_m, errors="coerce") > 0, dv_raw_m / foot_m, np.nan)
        base[f"DV1_abs_cm_{event}"] = dv_raw_m * 100.0

    compute_dv_for_event("platform_onset")
    compute_dv_for_event("step_onset")

    analysis_df = base[TRIAL_KEYS + ["step_TF", "DV1_norm_platform_onset", "DV1_norm_step_onset", "DV1_abs_cm_platform_onset", "DV1_abs_cm_step_onset"]].copy()
    analysis_df["step_TF"] = analysis_df["step_TF"].astype(str).str.strip().str.lower()
    analysis_df = analysis_df[analysis_df["step_TF"].isin(["step", "nonstep"])].reset_index(drop=True)

    if args.dry_run:
        print("[DRY] rows:", len(analysis_df))
        print("[DRY] subjects:", analysis_df["subject"].nunique())
        print("[DRY] step:", int((analysis_df["step_TF"] == "step").sum()), "nonstep:", int((analysis_df["step_TF"] == "nonstep").sum()))
        return

    dv_cols = [
        "DV1_norm_platform_onset",
        "DV1_norm_step_onset",
        "DV1_abs_cm_platform_onset",
        "DV1_abs_cm_step_onset",
    ]
    results = fit_lmm_all(analysis_df, dv_cols=dv_cols, timeout_sec=int(args.timeout_sec))

    out_dir = Path(args.out_dir)
    out_csv = out_dir / "tmp_raw_dv1_norm_vs_cm_lmm_results.csv"
    write_utf8_sig_csv(results, out_csv)

    print(f"[OK] results: {out_csv}")
    print(
        "[INFO] counts: "
        f"trials={len(analysis_df)}, subjects={analysis_df['subject'].nunique()}, "
        f"step={(analysis_df['step_TF']=='step').sum()}, nonstep={(analysis_df['step_TF']=='nonstep').sum()}"
    )


if __name__ == "__main__":
    main()
